---
apiVersion: v1
kind: ServiceAccount

metadata:
    name: {{ .Release.Name }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
    name: {{ .Release.Name }}

rules:
-   apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
-   apiGroups: [""]
    resources: ["services", "nodes"]
    verbs: ["get", "list", "watch"]
-   apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
-   apiGroups: ["switchboard.borchero.com"]
    resources: ["dnszones", "dnsrecords"]
    verbs: ["get", "list", "watch", "update"]
-   apiGroups: ["switchboard.borchero.com"]
    resources: ["dnszones/status", "dnsresources/status"]
    verbs: ["update"]
-   apiGroups: ["switchboard.borchero.com"]
    resources: ["dnszonerecords", "dnsresources"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
    name: {{ .Release.Name }}

roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ .Release.Name }}

subjects:
-   kind: ServiceAccount
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
