---
apiVersion: apps/v1
kind: Deployment

metadata:
    name: {{ .Release.Name }}
    labels:
        app.kubernetes.io/name: {{ .Release.Name }}

spec:
    replicas: {{ .Values.replicas }}
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ .Release.Name }}

    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ .Release.Name }}

        spec:
            serviceAccountName: {{ .Release.Name }}
            containers:
            -   name: switchboard
                image: {{ .Values.image.name }}:{{ .Values.image.tag }}
                imagePullPolicy: {{ .Values.image.pullPolicy }}
                {{- if gt .Values.replicas 1.0 }}
                args: ["--enable-leader-election"]
                {{- end }}
                # readinessProbe:
                #     httpGet:
                #         path: /readyz
                #         port: 8080
                # livenessProbe:
                #     httpGet:
                #         path: /healthz
                #         port: 8080
                #     periodSeconds: 30
                resources:
{{ toYaml .Values.resources | indent 20 }}
